### ISSUE TITLE
How I can disable half-star selection ?

### ISSUE THREAD

**Issue by sg-mamedova** [hughjdavey/ngx-stars#1]
Hey!
How I can disable half-star selection?
I nee only a full number of the star selection

**Comment by hughjdavey** [comment]
Hi! There isn't a way to do this currently, but I will try and get it in an update this weekend :)

**Comment by hughjdavey** [comment]
Hi again I managed to get it in this evening as it was only a small change. You should now be able to upgrade to version `1.3.0` and use the new `wholeStars` option. Like `<ngx-stars [readonly]="false" [maxStars]="5" [wholeStars]="true"></ngx-stars>`.

You can see a demo at https://hughjdavey.github.io/ngx-stars
