### ISSUE TITLE
ngx-stars support for angular 12

### ISSUE THREAD

**Issue by SagarUkrande-GSLab** [hughjdavey/ngx-stars#11]
Hey

Getting below error for ngx-stars with 1.5.1 version on angular 12. same issue persist for lasted version which is 1.6.3. Please check

TypeError: Cannot create property 'message' on string '..ngx-stars/fesm2015/ngx-stars.mjs: This application depends upon a library published using Angular version 14.0.0, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
![image](https://user-images.githubusercontent.com/13540211/173897073-a125cf89-b65d-49e6-8b92-7de323f57a71.png)

**Comment by hughjdavey** [comment]
Hi thanks for reporting I will take a look. I am suprised to hear this about 1.5.1 as that was published in April 2021 which was before Angular 12 was out, so it's weird it would be asking you to upgrade your Angular. In the case of 1.6.3 I built it with Angualr 14 so that may be the issue

**Comment by hughjdavey** [comment]
Hi I have tested on Angular versions 10, 11 and 12 and was able to reproduce your error with verison 1.6.3 on all of them. However 1.5.1 works on all of them in my testing. So I am going to look into the problem with 1.6.3 but you should be able to use 1.5.1 for now. If not could you recreate the issue in an Angular 12 project and send to me? I was using v12-lts (12.2.17).

**Comment by hughjdavey** [comment]
From googling I can't see a way to produce a build that supports all versions of Angular - I think I may just have to add a compatibility table to the README, where <= Angular 13 has to use 1.5.1 or below. That is what e.g. this project is doing for the same issue https://github.com/kolkov/angular-editor/issues/464
