### ISSUE TITLE
Selecting a half star in RTL mode

### ISSUE THREAD

**Issue by Linknpay** [hughjdavey/ngx-stars#13]
Hello there is an issue with stars in RTL mode.
When you select a half star: The half in the left is full and it should be the right half.
Please check the picture attached
![Capture d’écran 2023-02-24 à 17 28 04](https://user-images.githubusercontent.com/11230174/221233785-3fca27f5-02ff-4481-8e8e-56e71c8acdbd.png)

Thank you

**Comment by hughjdavey** [comment]
Hi thanks for raising this issue. I admit I never tested RTL layouts which I should have done. You are welcome to raise a PR if you have the solution? Otherwise I will take a look at this when I get time in the next week or two.

**Comment by github-sadegh** [comment]
Hi. I have the same issue to use this library in RTL websites.
Did you find a solution for this?

**Comment by hughjdavey** [comment]
Hi @github-sadegh thanks for confirming you have the issue too. I plan to look at it at the weekend.

**Comment by hughjdavey** [comment]
Hi both I have now released [v1.6.5](https://www.npmjs.com/package/ngx-stars) which has a new `@Input` boolean `rtl`. It fixes the half star images and also places the 'zero star' (that you click to set to 0) on the right hand side. But you might need to have the star component in an LTR section for it to work, as it relies on flipping images around, so if it was in a `dir="rtl"` section it would flip back again to be incorrect.

Please let me know if this is a suitable fix. I am happy to discuss other implementations if that would be better for your use-cases.
