### ISSUE TITLE
I can't update the value of intialStars via data binding, only by clicking.

### ISSUE THREAD

**Issue by nyszilard** [hughjdavey/ngx-stars#14]
Its name suggests that this is intentional, but it would be nice to be able to update its value not just by clicking.

You can solve it that way:
```ts
ngOnChanges(changes: SimpleChanges): void {
  if (changes.initialStars) {
    this.rating = this.initialStars;
    this.setRating(this.rating);
  }
}
```

**Comment by hughjdavey** [comment]
Hi @nyszilard thanks for the issue. I am not sure I understand what you mean? Are you having trouble using the `[initialStars]` property? Initial stars is just meant to be the starting value of the stars, when the page loads - as you show in your code, you can update the stars any time by calling `setRating`. Or am I misundertanding you? What are you trying to do?

**Comment by hughjdavey** [comment]
Are you able to provide any more info on this?
