### ISSUE TITLE
Unable to reset in reactive forms.

### ISSUE THREAD

**Issue by ultimateakash** [hughjdavey/ngx-stars#5]
I am trying to reset the value of form control but its not working. please help me.

**Comment by hughjdavey** [comment]
Hi @ultimateakash can you give a few more details? Maybe post (simplified if you like) version of your component HTML and ts files?

**Comment by ultimateakash** [comment]
I am user Angular 9.   
"ngx-stars": "^1.4.3",

```html
<ngx-stars class="star-group form-control " [color]="'#ffc107'" (ratingOutput)="onRatingSet($event)" formControlName="rating" ngDefaultControl></ngx-stars>
```
```js
this.filterForm = this.fb.group({
      company: [''],
      postalCode: [''],
      city: [''],
      radius: [''],
      rating: ['']
    });
````
On Reset
```js
this.filterForm.reset();                                          // not working
this.filterForm.get('rating')?.setValue(0);              // not working
```

**Comment by hughjdavey** [comment]
Oh I think I understand. `ngx-stars` is unfortunately not an `NgForm` component so you can't reset it by resetting the form. However you can call the `NgxStarsComponent` `setRating` method to set any value you like at any time. Using Angular's `@ViewChild` for example you could do (in your ts file):

```typescript
export class MyComponent {

  @ViewChild(NgxStarsComponent)
  starsComponent: NgxStarsComponent;

  ...

  // when you want to reset the form
  // do form reset as normal
  // and then call
  this.starsComponent.setRating(0);
}
```

Does that make sense? You can also pass any number to `setRating`, not just 0. I should update the docs to make this method clearer. Let me know if it works for you.

**Comment by ultimateakash** [comment]
@hughjdavey  Thank you so much for your quick response. yeah its working fine. but its better if there is another way to reset it  without viewchild. anyway thanks.

**Comment by hughjdavey** [comment]
No worries! When I get some time I'll take a look about improving the documentation and maybe adding an `NgForm` integration, enabling it to be reset when a form is reset.
