### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by Linknpay** [hughjdavey/ngx-stars#9]
Size between 1 to 5 is not very adapted to all projects.
Can you let us choose the number of px instead

**Comment by hughjdavey** [comment]
I am sure this can be made configurable let me look into it

**Comment by hughjdavey** [comment]
Added new `customSize` input for the component. Let me know what you think. Use like
```html
<ngx-stars customSize="24px"></ngx-stars>
<ngx-stars customSize="5vh"</ngx-stars>
<ngx-stars customSize="4rem"></ngx-stars>
```
